version: '3.8'

services:
  mysql:
    image: mysql:${DATABASE_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - coworking-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  coworking-api:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${SERVER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SERVER_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SERVER_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coworking-network

networks:
  coworking-network:
    driver: ${DOCKER_DRIVER}

